### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by burnflare** [launchdarkly/ios-client#103]
Is the LaunchDarkly SDK thread safe? We've been noticing some crashes when `[LDClient boolVariation]` is called from another thread.

```
#10. Crashed
0  libobjc.A.dylib                0x1870981a0 objc_retain + 16
1  Darkly                         0x10185d228 -[LDUserModel flagValue:] + 60
2  Darkly                         0x1018579c0 -[LDClient boolVariation:fallback:] + 216
```

Should we not be doing this?

**Comment by arun251** [comment]
Hi @burnflare, the SDK is intended to be used by multiple threads. Can you tell us which version of the SDK you are using where you see this issue? Feel free to continue using the support@launchdarkly.com channel.

**Comment by arun251** [comment]
As far as we know, this is obsolete. Please leave a comment if you're still seeing this with iOS SDK 2.4.2 or later.
