### ISSUE TITLE
Capacity for Events

### ISSUE THREAD

**Issue by jeff-byrnesinnovation** [launchdarkly/ios-client#12]
@jkodumal 

In working on the configuration issue, @gus-byrnesinnovation and I noticed that we are not using the capacity value that can be passed in via configBuilder on starting the client. We wanted to confirm what this capacity means. Our interpretation is that when events are persisted we confirm that the collection of events is less than this value. We then disregard any events that occur after. When, the next flush happens, the persisted events will be cleared out, and then we will begin persisting again. Is this understanding correct?

**Comment by jkodumal** [comment]
That's correct-- if you look at any of the other open-source
implementations that's exactly how they behave.

**Comment by jeff-byrnesinnovation** [comment]
@jkodumal this has now been merged into master
