### ISSUE TITLE
No known class method for selector 'eventSourceWithURL:httpHeaders:connectMethod:connectBody:'

### ISSUE THREAD

**Issue by mikeono** [launchdarkly/ios-client#129]
STEPS TO REPRO:

1) Install 2.11.0 into an iOS app by adding the following line to your pod file: 
    `pod 'LaunchDarkly', :git => 'https://github.com/launchdarkly/ios-client.git', :tag => '2.11.0'`

2) Run `pod install`

3) Build

4) Compiler will complain with:

`LDClientManager.m:162:38: No known class method for selector 'eventSourceWithURL:httpHeaders:connectMethod:connectBody:'`

**Comment by mikeono** [comment]
@markpokornycos This may be related to https://github.com/launchdarkly/ios-client/commit/4c921d9991062097ac36654016df141142f200f8

**Comment by markpokornycos** [comment]
@mikeono Thanks for pointing this out! I will work on resolving this into a new version. In the mean time there is a work-around. You should be able to modify your podfile to add the dependency to the DarklyEventSource version needed:
```
    pod 'DarklyEventSource', '3.2.0'
```

**Comment by markpokornycos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CocoaPods doesn't specify DarklyEventSource](https://trello.com/c/vyqnDELT/114-cocoapods-doesnt-specify-darklyeventsource)

**Comment by arun251** [comment]
Hi @mikeono, thanks for reporting the issue. We've released a fix in iOS SDK 2.11.1.
