### ISSUE TITLE
Watchdog timeout for performEventRequest

### ISSUE THREAD

**Issue by brandenlivermore** [launchdarkly/ios-client#134]
I recently noticed a watchdog crash with the message `exhausted real (wall clock) time allowance of 10.00 seconds` and the stack trace was inside of the Darkly library in `LDRequestManager`'s ` - (void)performFeatureFlagRequest:(NSString *)encodedUser`. 

A semaphore is used to block until the network request finishes. The default timeout, according to the comment in `LDConfig.h` is 10 seconds, enough to trigger the watchdog to kill the app if the network request doesn't finish before the timeout. As a workaround, I've set the timeout to something less than 10 seconds, but I was hoping for a more permanent solution that doesn't involve blocking the main thread.

**Comment by markpokornycos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate Flag Request blocking issue](https://trello.com/c/KJigwyPf/136-investigate-flag-request-blocking-issue)

**Comment by arun251** [comment]
Hi @brandenlivermore , thanks for reporting the issue. Up through version 2.7.0, there is a semaphore that blocks the thread the LDClient runs on while flag requests are in progress. With version 2.8.0, the semaphore was removed. If you're not currently using version 2.8.0 or later, we recommend you update the SDK to the latest version and retest to see if the watchdog crash continues. If it does, please post the details of the crash so we can help resolve the issue. As always, feel free to reach out to support@launchdarkly.com.

**Comment by arun251** [comment]
Thanks for confirming. I'll close this issue for now, but let us know if you see it in 2.12.1.
