### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by BohdanOrlov** [launchdarkly/ios-client#136]
Hey, guys!

It looks like semantic versioning support was added for other platform SDKs, are there any plans for adding it into iOS SDK?

Not having semantic versioning forces developers to manually opt-in/opt-out each specific version which is prone to human error (and boring 😅).

**Comment by BohdanOrlov** [comment]
Hey, @arun251!
I've contacted your support about a week ago:

![image](https://user-images.githubusercontent.com/6740223/41604513-5b507ad6-73d7-11e8-9d2d-efc31436e794.png)

The image I've attached in that thread:
![image](https://user-images.githubusercontent.com/6740223/41604551-6c48a7c8-73d7-11e8-94e2-1a2e650ecc77.png)

Could you please help understand what is going on?

**Comment by arun251** [comment]
Hi @BohdanOrlov 
No updates are required for iOS SDK. Our Support team will contact you for enabling the semantic versioning feature.
