### ISSUE TITLE
Race on library object

### ISSUE THREAD

**Issue by kristiyandobrev** [launchdarkly/ios-client#137]
I have update to `2.13.0` and soon after taht the Thread sanitizer started warning me for a race condition in `LDDataManager` class on line `267`:
 
<img width="1580" alt="screen shot 2018-06-19 at 16 02 59" src="https://user-images.githubusercontent.com/8437817/41602303-ce59a400-73da-11e8-9d4e-0bef272bfded.png">

**Comment by markpokornycos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LDDataManager race condition on adding events](https://trello.com/c/Kyle9V9V/169-lddatamanager-race-condition-on-adding-events)

**Comment by arun251** [comment]
Hi @kristiyandobrev 
We've analyzed the code referenced by Thread Sanitizer and determined this to be a benign race condition with no harmful effects. As a result, we are not treating this as a critical issue and will fix it in the next 1-2 weeks. Let us know if that causes a problem for you.

**Comment by arun251** [comment]
@kristiyandobrev We've resolved these warnings in 2.13.1.
