### ISSUE TITLE
`updateUser` does not attempt to load cached flag information

### ISSUE THREAD

**Issue by bradleyrzeller** [launchdarkly/ios-client#146]
Is it intentional to not load cached flag info when calling `updateUser`? Flag info is only loaded from cache upon starting the client.

In our application, we start the client immediately on app launch with an anonymous user. Shortly after, when we know who the user is, we update the user with `updateUser`. However, as mentioned, the client does not load flag info from cache which will revert all flags back to their default state until they are retrieved again from the network. Obviously, this is particularly problematic when launching offline.

I would expect that calls to `updateUser` would load flag info from cache, if present.

Thanks for the help.

**Comment by arun251** [comment]
Hi @bradleyrzeller,

We've fixed this in version 2.13.6. Let us know if that resolves your issue.

**Comment by bradleyrzeller** [comment]
Thanks @arun251. I'll let you know once we update.
