### ISSUE TITLE
Crash - [LDClientManager syncWithServerForEvents]

### ISSUE THREAD

**Issue by leaveleafs** [launchdarkly/ios-client#155]
Hello, my team has been experiencing a crash in iOS Client version 2.13.9. This is an iOS app. We have seen about 50 of these crashes in the past month. We have not been able to reproduce it locally. Not sure if it matters but this crash happens off the main thread.

I think this may be the same issue as #141 but it appears the fix that went into version 2.13.3 did not work for us. 

Stack Trace: 
```
0  libobjc.A.dylib                0x181a7f6f0 objc_retain + 16
1  LaunchDarkly                   0x105a7279c -[LDClientManager syncWithServerForEvents] (LDClientManager.m:319)
2  LaunchDarkly                   0x105a7e2d0 -[LDPollingManager eventPoll] (LDPollingManager.m:216)
3  libdispatch.dylib              0x1822712f0 _dispatch_client_callout + 20
4  (Missing)                      0x371281822742c0 (Missing)
5  (Missing)                      0x381d8182284410 (Missing)
6  (Missing)                      0x1dc10182283c90 (Missing)
7  (Missing)                      0x31bb81822800d4 (Missing)
8  (Missing)                      0x43878182280940 (Missing)
9  (Missing)                      0x6e390182470bc0 (Missing)
10 (Missing)                      0x61998182476dd4 (Missing)

line 319 
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000002307ac60
```
From Podfile.lock:
```
  - LaunchDarkly (2.13.9):
    - LaunchDarkly/Core (= 2.13.9)
  - LaunchDarkly/Core (2.13.9):
    - DarklyEventSource (~> 3.2.7)
```

**Comment by arun251** [comment]
Thanks @leaveleafs . We'll take a look. If you have any more information you can share that could be helpful, please let us know. If the information might be sensitive, feel free to reach out to support@launchdarkly.com.

**Comment by leaveleafs** [comment]
Thank you for looking into this @arun251! At the moment I'm not sure what else would be helpful but we are seeing that the crash has only happened on devices running iOS 12.

**Comment by arun251** [comment]
Hi @leaveleafs , we released 2.14.1 with some refactoring and additional synchronization. Please let us know if you continue to see issues after upgrading to this version.

**Comment by leaveleafs** [comment]
Awesome! We will update the pod and I'll report back after its been in the wild for a few days.

**Comment by leaveleafs** [comment]
Hello @arun251 , With the latest version of LD we are no longer seeing this crash. Closing this issue.
