### ISSUE TITLE
Cannot access ldUser from LDClient

### ISSUE THREAD

**Issue by joehsieh** [launchdarkly/ios-client#159]
I cannot access `ldUser` from LDClient anymore since 2.14.0.
I think that's because `#import <Darkly/LDUserModel.h>` is not in `Darkly.h` anymore.

**Comment by arun251** [comment]
Hi @joehsieh -- that is correct. `ldUser` and `LDUserModel` were never intended to be exposed to SDK consumers. We made this change to make it more clear which classes/methods/properties were intended to be private. You can access the equivalent of `ldUser` with `[[LDClient sharedInstance] currentUserBuilder]`.
