### ISSUE TITLE
Carthage Based Build Fails App Store Validation

### ISSUE THREAD

**Issue by spr** [launchdarkly/ios-client#217]
**Is this a support request?**
No

**Describe the bug**
If you use LaunchDarkly 5.0.1 as a dependency to your project via Carthage, and submit your .xcarchive file to the App Store for validation, you receive the following validation failures:
- Invalid Bundle. The bundle at 'yourapp.app/Frameworks/LaunchDarkly.framework' contains disallowed nested bundles.
- Invalid Bundle. The bundle at 'yourapp.app/Frameworks/LaunchDarkly.framework' contains disallowed file 'Frameworks'.

**To reproduce**
Steps to reproduce the behavior.
1. Create Project
2. Add LaunchDarkly via Carthage
3. Generate an archive
4. "Validate App" in the Xcode organizer

**Expected behavior**
App should pass validation

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
The version of this SDK that you are using.
5.0.1

**Language version, developer tools**
Xcode 11.6

**OS/platform**
macOS 10.15.5

**Additional context**

The LaunchDarkly framework is embedding the LDSwiftEventSource framework. It shouldn't do that, LDSwiftEventSource should be added directly to the top level project.

**Comment by gwhelanLD** [comment]
Hi @spr,

Thanks for also testing this in Carthage. Like https://github.com/launchdarkly/ios-client-sdk/issues/216, we will also prioritize including a fix for this in 5.1 to resolve the app store submission rejection error. We appreciate your detailed reports!

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
Hi @spr,

We've just released [5.1.0](https://github.com/launchdarkly/ios-client-sdk/releases/tag/5.1.0) which should resolve this issue. Please give it a try and let us know if you run into any issues.

Thanks!
@gwhelanLD

**Comment by spr** [comment]
Passes validation now, thank you!
