### ISSUE TITLE
LDEventSource mutable array bug

### ISSUE THREAD

**Issue by RangerRick** [launchdarkly/ios-client#222]
**Describe the bug**
This is actually for the [ios-eventsource](https://github.com/launchdarkly/ios-eventsource) project but you don't have issue-tracking enabled there so I wanted to make sure there was an issue for my PR.

If you attempt to remove listeners while events are being processed, you can get an `NSArray` "mutated while being enumerated" error.

**To reproduce**
call `LDEventSource.removeListener()` while messages are being processed.

**Expected behavior**
No crash.

**Logs**
I have rebuilt since then so I don't have logs, sorry.  If you need them to close this, let me know and I'll try reproducing it.

**Fix**
I've had the code from [my PR](https://github.com/launchdarkly/ios-eventsource/pull/32) running for a couple hours now and haven't seen the crash, so I think this handles it.

**Comment by gwhelanLD** [comment]
Thanks again for the PR, I've merged it in `ios-eventsource`. I've also enabled issues on the repository. I'll close this issue now, as the SDK should not be effected.
