### ISSUE TITLE
In debug mode,  minimum refresh interval should be set to 100ms

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/ios-client#23]
Currently, in debug mode, the flag configuration resource will be polled as quickly as possible. As a result, there is no upper bound on the number of requests per second an individual client can make.

Instead, in debug mode, we would like to impose a minimum 100ms delay on re-polling. The logic should be:

1) In production, respect the TTL, or if the TTL is 0, treat the TTL as 1 minute
2) In debug mode, respect the TTL, or if the TTL is 0, treat the TTL as 100ms

**Comment by jeff-byrnesinnovation** [comment]
This is fixed in the pull request for https://github.com/launchdarkly/ios-client/pull/30.

1) When config is 0, on non-debug it is set to 1 min
2) When config is 0, on debug it is set to 100 ms
3) When event is 0, on debug or non-debug it is set to 30 sec
