### ISSUE TITLE
SwiftPM - Tools Version 5.2

### ISSUE THREAD

**Issue by escakot** [launchdarkly/ios-client#233]
**Is your feature request related to a problem? Please describe.**
Importing the LD SDK through SwiftPM will import dev/test dependencies which is not ideal.
![image](https://user-images.githubusercontent.com/4576455/103885117-88d29b00-50ad-11eb-9400-f80b3e5b29e7.png)

**Describe the solution you'd like**
Updating to Swift Tools 5.2 and minor changes to `Package.swift` will resolve this. I've tested it on my own fork. Let me know if you would like to me to make a PR.
![image](https://user-images.githubusercontent.com/4576455/103885250-b6b7df80-50ad-11eb-911c-e70f6ac4e717.png)

**Describe alternatives you've considered**
N/A

**Additional context**
We're currently using Carthage to install the LD sdk. We're planning to switch over to SwiftPM soon.

**Comment by gwhelanLD** [comment]
Hi @escakot,

Great suggestion, we'd love to see a PR for this. We'd just need to verify that it should work across the various supported installation methods. Hopefully this sort of change should only reduce the complexity of including the SDK within applications.

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
Thanks again for your PR! I'm closing this issue now that it's been included in the [5.4.2 release](https://github.com/launchdarkly/ios-client-sdk/releases/tag/5.4.2).

Thanks,
@gwhelanLD
