### ISSUE TITLE
Crash in LDClient.swift:143

### ISSUE THREAD

**Issue by maciejtrybilo** [launchdarkly/ios-client#236]
**Describe the bug**
We've received a following crash report

`Incident Identifier: 6bd47464-3144-4e44-a154-622ac8027fd8
CrashReporter Key:   D656D0BB-0F99-4E45-BC7A-4DAAE5D5B57F
Hardware Model:      iPhone11,8
Process:         App-Name [29794]
Code Type:       arm64
Parent Process:   [1]

Date/Time:       2021-02-02T10:45:58.999Z
Launch Time:     2021-02-02T10:45:55Z
OS Version:      iPhone OS 14.3 (18C66)
Report Version:  104

Exception Type:  SIGTRAP
Exception Codes: TRAP_BRKPT at 0x193ff17d8
Crashed Thread:  0

Thread 0 Crashed:
0   libdispatch.dylib                    0x0000000193ff17d8 dispatch_group_leave.cold.1 + 36
1   libdispatch.dylib                    0x0000000193fbec00 dispatch_group_leave + 136
2   LaunchDarkly                         0x0000000106db9adc partial apply forwarder for closure #2 () -> () in LaunchDarkly.LDClient.(go in _14C52C04C80D938C2FE76924F7908AD1)(online: Swift.Bool, reasonOnlineUnavailable: Swift.String, completion: () -> ()?) -> () (LDClient.swift:143)
3   LaunchDarkly                         0x0000000106d99190 partial apply forwarder for closure #1 () -> () in closure #1 (LaunchDarkly.FlagsUnchangedObserver) -> () in closure #1 () -> () in LaunchDarkly.FlagChangeNotifier.notifyObservers(flagStore: LaunchDarkly.FlagMaintaining, oldFlags: [Swift.String : LaunchDarkly.FeatureFlag]) -> () (FlagChangeNotifier.swift:94)
4   LaunchDarkly                         0x0000000106d760a0 reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () (<compiler-generated>:0)
5   libdispatch.dylib                    0x0000000193fbc24c _dispatch_call_block_and_release + 28
6   libdispatch.dylib                    0x0000000193fbddb0 _dispatch_client_callout + 16
7   libdispatch.dylib                    0x0000000193fcb7ac _dispatch_main_queue_callback_4CF + 832
8   CoreFoundation                       0x000000019434511c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
9   CoreFoundation                       0x000000019433f120 __CFRunLoopRun + 2504
10  CoreFoundation                       0x000000019433e21c CFRunLoopRunSpecific + 596
11  GraphicsServices                     0x00000001abe42784 GSEventRunModal + 160
12  UIKitCore                            0x0000000196d7cfe0 -[UIApplication _run] + 1068
13  UIKitCore                            0x0000000196d82854 UIApplicationMain + 164
14  App-Name                0x0000000104f6712c main (AppDelegate.swift:19)
15  libdyld.dylib                        0x0000000193ffe6b0 start + 0

Thread 1:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 2:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 3:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 4:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 5:
0   libsystem_pthread.dylib              0x00000001dfba2754 start_wqthread + 0

Thread 6:
0   libsystem_kernel.dylib               0x00000001c211c2d0 mach_msg_trap + 8
1   CoreFoundation                       0x0000000194344c30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019433ec14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019433e21c CFRunLoopRunSpecific + 596
4   Foundation                           0x00000001955eddf0 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
5   Foundation                           0x00000001955edcbc -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
6   UIKitCore                            0x0000000196e30d48 -[UIEventFetcher threadMain] + 512
7   Foundation                           0x000000019575fa34 __NSThread__start__ + 860
8   libsystem_pthread.dylib              0x00000001dfb99b40 _pthread_start + 316
9   libsystem_pthread.dylib              0x00000001dfba2768 thread_start + 4

Thread 7:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 8:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 9:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 10:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 11:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 12:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 13:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 14:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 15:
0   libsystem_kernel.dylib               0x00000001c2141184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001dfba275c start_wqthread + 4

Thread 16:
0   App-Name                0x0000000105391838 mach_exception_callback (PLCrashReporter.m:291)
1   App-Name                0x00000001053a076c exception_server_thread (PLCrashMachExceptionServer.m:770)
2   libsystem_pthread.dylib              0x00000001dfb99b40 _pthread_start + 316
3   libsystem_pthread.dylib              0x00000001dfba2768 thread_start + 4

Thread 17:
0   libsystem_kernel.dylib               0x00000001c211c2d0 mach_msg_trap + 8
1   CoreFoundation                       0x0000000194344c30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019433ec14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019433e21c CFRunLoopRunSpecific + 596
4   CFNetwork                            0x0000000194c142c0 _CFURLStorageSessionCopyCache + 64448
5   Foundation                           0x000000019575fa34 __NSThread__start__ + 860
6   libsystem_pthread.dylib              0x00000001dfb99b40 _pthread_start + 316
7   libsystem_pthread.dylib              0x00000001dfba2768 thread_start + 4

Thread 18:
0   libsystem_kernel.dylib               0x00000001c211c2d0 mach_msg_trap + 8
1   CoreFoundation                       0x0000000194344c30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019433ec14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019433e21c CFRunLoopRunSpecific + 596
4   Foundation                           0x00000001955eddf0 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
5   App-Name                0x00000001057b73a8 -[GMSx_GTMSimpleWorkerThread main] + 180
6   Foundation                           0x000000019575fa34 __NSThread__start__ + 860
7   libsystem_pthread.dylib              0x00000001dfb99b40 _pthread_start + 316
8   libsystem_pthread.dylib              0x00000001dfba2768 thread_start + 4

Thread 0 crashed with arm64 Thread State:
   x21: 0x00000002803d0760     x2: 0x0000000000000002    x16: 0x0000000193fbeb74     x3: 0x00000001a411acdc
   x22: 0x00000002817c26c0     x4: 0x00000000000062dc    x17: 0x0000000016a00000   cpsr: 0x0000000000000000
    x5: 0x0000000000000001    x23: 0x0000000000000000     x6: 0x0000000000000003    x18: 0x000000010f9dcac0
   x10: 0x0000000000000070     lr: 0x0000000193fbec00     x7: 0x0000000000000004    x24: 0x0000000002ffffff
   x11: 0x0000000000000100     x8: 0x0000000000000000    x19: 0x000000010885ee00    x25: 0x000000010644b9a0
    x9: 0x0000000000000004    x12: 0x0000000000002000     fp: 0x000000016aea29c0    x26: 0x00000000000020ff
   x13: 0x000000009683c020     pc: 0x0000000193ff17d8    x27: 0x0000000000000114    x14: 0x0000000096a3c800
   x20: 0x0000000280224060     x0: 0x0000000000000000     sp: 0x000000016aea29c0    x28: 0x00000002817c26c0
   x15: 0x0000000000000079     x1: 0x0000000193fbc22c
`

**To reproduce**
I'm not able to reproduce, but the report came in just after I made some changes in the portal. Not sure if it's related.

**Expected behavior**
No crash.

**SDK version**
5.3.1

**Comment by bwoskow-ld** [comment]
Hi @maciejtrybilo ,

This looks like the same problem as described in #235. I'm going to close this -- let's consolidate the conversation over there.
