### ISSUE TITLE
Xcode warning Data Race in LD.DiagnosticReporter.isOnline.getter

### ISSUE THREAD

**Issue by provanandparanjape** [launchdarkly/ios-client#238]
**Describe the bug**
Thread Sanitizer detected "Data Race". No impact on functionality as of now.
<img width="894" alt="Data Race detected" src="https://user-images.githubusercontent.com/64438587/108773097-b5822b00-7512-11eb-93fe-f287b97c4ff3.png">

**To reproduce**
- Enable Thread sanitizer in XCode
- Run your app which uses LD SDK

**Expected behavior**
No warning

**Logs**
==================
WARNING: ThreadSanitizer: data race (pid=43449)
  Read of size 1 at 0x7b1c0002bb41 by thread T7:
    #0 $s12LaunchDarkly18DiagnosticReporterC8isOnlineSbvg <compiler-generated> (LaunchDarkly:x86_64+0x6aa84)
    #1 $s12LaunchDarkly18DiagnosticReporterC19maybeStartReporting33_D8E86B731A260FDA4BC4F57B0B3451E0LLyyF DiagnosticReporter.swift:68 (LaunchDarkly:x86_64+0x6bf74)
    #2 $s12LaunchDarkly18DiagnosticReporterC8isOnlineSbvWyycfU_ DiagnosticReporter.swift:50 (LaunchDarkly:x86_64+0x6aa18)
    #3 $s12LaunchDarkly18DiagnosticReporterC8isOnlineSbvWyycfU_TA <compiler-generated> (LaunchDarkly:x86_64+0x70d1d)
    #4 $sIeg_IeyB_TR <compiler-generated> (LaunchDarkly:x86_64+0x30d90)
    #5 __tsan::invoke_and_release_block(void*) <null>:4279024 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x6a89b)
    #6 _dispatch_client_callout <null>:4279024 (libdispatch.dylib:x86_64+0x2d47)

**SDK version**
5.3.1

**Language version, developer tools**
Swift

**OS/platform**
Xcode 11.3.1

**Comment by torchhound** [comment]
Hi @provanandparanjape thanks for reporting this.

_Filed internally as 101407_

**Comment by gwhelanLD** [comment]
Hi @provanandparanjape, 

Thanks for reporting this issue. We believe it should be resolved in the [5.4.0 release](https://github.com/launchdarkly/ios-client-sdk/releases/tag/5.4.0), so I'm going to close this issue for now. Feel free to reopen if the release does not correct the issue. 

Thanks,
@gwhelanLD
