### ISSUE TITLE
Swift wrapper

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/ios-client#24]
Add idiomatic Swift interfaces on top of the current Obj-C interfaces. To be delivered in two phases:

1) First, define the Swift interfaces and send out for feedback
2) Implement the Swift wrapper layer after incorporating feedback

**Comment by jkodumal** [comment]
One note: check the list of reserved keywords in Swift, and make sure the API is friendly wrt that. For example, `default` is a keyword in Swift, which makes `toggle` harder to call.

**Comment by kdawgwilk** [comment]
I would say they if the Objective-C had some better annotations it would work great with Swift and then there wouldn't be a need to write a Swift wrapper

**Comment by arun251** [comment]
We won't be writing a Swift wrapper, but we will be updating the SDK to be more Swift-friendly. Closing as obsolete.
