### ISSUE TITLE
[Help] Updating custom properties for an User

### ISSUE THREAD

**Issue by RuiAAPeres** [launchdarkly/ios-client#245]
I have a situation where I need to update a custom property for the user on a fairly regular basis. Is the best way to do this, by creating a new user every time?

**Comment by bwoskow-ld** [comment]
Hi @RuiAAPeres ,

I'm going to direct you to our support team for this inquiry -- you can get in touch with them by emailing support@launchdarkly.com. This issue tracker is intended for bugs and feature requests specific to this repository's code.

Cheers,
@bwoskow-ld
