### ISSUE TITLE
Alternate implementation of DataManager 

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/ios-client#25]
Feedback so far is that CoreData is a bit too heavyweight a dependency. Instead, provide an alternative implementation of the DataManager interface using either

1) Flat file storage
2) User preferences

Issues to consider:

1) Performance: the desired implementation should read / write flag / user configuration data from memory while the application is active, save data to a persistent store when the app is backgrounded, and restore data when the app is foregrounded.

2) Versioning: over time we may need to change our data storage schema. When we do this, we will want existing clients to discard persisted data if the schema is out of date.

**Comment by drichelson** [comment]
Resolved in 1.0.0
