### ISSUE TITLE
Crashed: com.launchdarkly.LDClient.isOnlineQueue

### ISSUE THREAD

**Issue by chkkassd** [launchdarkly/ios-client#250]
hi,I meet a crash.
My iOS project is a swift project using LaunchDarkly pod
Xcode: 12.4
`pod 'LaunchDarkly', '5.4.0'`

The crash stack trace is blew:

> Crashed: com.launchdarkly.LDClient.isOnlineQueue
0  libobjc.A.dylib                0x19df8ec80 objc_retain + 16
1  LaunchDarkly                   0x1039e2480 $s12LaunchDarkly16FlagSynchronizerC8isOnlineSbvs + 204
2  LaunchDarkly                   0x1039e4450 $s12LaunchDarkly16FlagSynchronizerCAA19LDFlagSynchronizingA2aDP8isOnlineSbvsTW + 24
3  LaunchDarkly                   0x1039e8db0 $s12LaunchDarkly8LDClientC8isOnlineSbvsyyXEfU_ + 180
4  LaunchDarkly                   0x1039f3434 $sIg_Ieg_TRTA + 20
5  LaunchDarkly                   0x1039e8918 $sIeg_IyB_TR + 20
6  libdispatch.dylib              0x1890b781c _dispatch_client_callout + 20
7  libdispatch.dylib              0x1890c6910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
8  LaunchDarkly                   0x1039e98d4 $s12LaunchDarkly8LDClientC2go33_14C52C04C80D938C2FE76924F7908AD1LL6online23reasonOnlineUnavailable10completionySb_SSyycSgtF + 1312
9  LaunchDarkly                   0x1039f7764 $s12LaunchDarkly8LDClientC17internalSetOnline33_14C52C04C80D938C2FE76924F7908AD1LL_10completionySb_yycSgtFyyXEfU_yycfU_TA + 100
10 LaunchDarkly                   0x103a2002c $sIeg_IeyB_TR + 20
11 libdispatch.dylib              0x1890b5a84 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x1890b781c _dispatch_client_callout + 20
13 libdispatch.dylib              0x1890c910c _dispatch_root_queue_drain + 688
14 libdispatch.dylib              0x1890c97d8 _dispatch_worker_thread2 + 112
15 libsystem_pthread.dylib        0x1d502e768 _pthread_wqthread + 216
16 libsystem_pthread.dylib        0x1d503574c start_wqthread + 8

Can anybody help me?

**Comment by bwoskow-ld** [comment]
Hi @chkkassd ,

I see that you've also filed a ticket with LaunchDarkly's support team and have an ongoing conversation there. Rather than split our communications with you, let's consolidate the conversation there. Our engineering team is in contact with the support team.

Cheers,
@bwoskow-ld

**Comment by chkkassd** [comment]
> Hi @chkkassd ,
> 
> I see that you've also filed a ticket with LaunchDarkly's support team and have an ongoing conversation there. Rather than split our communications with you, let's consolidate the conversation there. Our engineering team is in contact with the support team.
> 
> Cheers,
> @bwoskow-ld

Thanks.
