### ISSUE TITLE
LDClient.start timeout when using DBDebugToolkit

### ISSUE THREAD

**Issue by rweindl** [launchdarkly/ios-client#251]
We are currently evaluating LaunchDarkly and run into the following issue:
When using LaunchDarkly in parallel to frameworks like DBDebugToolkit we receive a timeout when calling `LDClient.start`. DBDebugToolkit integrates well with every other framework we are using. 

 I attached an example project demonstrating this issue. Open the evaluation.xcworkspace and please provide a mobile key in the AppDelegate.swift.

Thanks for looking into that.

[evaluation.zip](https://github.com/launchdarkly/ios-client-sdk/files/6778771/evaluation.zip)

**Comment by m1entus** [comment]
Seems can be related to https://github.com/dbukowski/DBDebugToolkit/issues/25

**Comment by gwhelanLD** [comment]
Thanks @m1entus for the related issue! That definitely looks like it would be the problem here. All I can recommend for @rweindl at this time would be to use the SDK only in polling mode when integrating `DBDebugToolkit` alongside the SDK.

Thanks,
@gwhelanLD
