### ISSUE TITLE
Xcode 13 Swift Package Manager Warnings

### ISSUE THREAD

**Issue by kriss-campbell** [launchdarkly/ios-client#255]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
New warning messages appear when building & resolving packages containing the iOS SDK with Xcode 13:

**To reproduce**
Build workspace containing Launch Darkly iOS SDK (version 5.4.3) in Xcode 13

**Expected behavior**
Warnings do not appear

**Logs**
Invalid Resource 'Resources': File not found.Invalid Exclude '...SourcePackages/checkouts/ios-library/Airship/AirshipCore/Resources/Info.plist': File not found.
Invalid Exclude '...SourcePackages/checkouts/ios-library/Airship/AirshipExtendedActions/Resources/Info.plist': File not found.
Invalid Resource 'Resources': File not found.
Invalid Exclude '...SourcePackages/checkouts/ios-library/Airship/AirshipAutomation/Resources/Info.plist': File not found.
Invalid Exclude '...SourcePackages/checkouts/ios-library/Airship/AirshipMessageCenter/Resources/Info.plist': File not found.

**SDK version**
5.4.3

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.
Swift 5.5/SwiftUI 3.0

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

macOS Big Sur 11.6

**Additional context**

**Comment by gwhelanLD** [comment]
Hi @kriss-campbell,

Thanks for letting us know you're seeing warnings with Xcode 13, we're currently going through our SDKs that use Xcode to validate them against any issues. We'll let you know soon if we've resolved this issue, or if we have any trouble reproducing.

Thanks!
@gwhelanLD

**Comment by gwhelanLD** [comment]
I've been unable to reproduce this with our test applications, and the warning messages don't seem to refer to anything from the SDK. Is it possible this is an issue with another dependency, or occurs if you've included any dependency as a swift package?

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
Hi @kriss-campbell,

Since we haven't heard back from you, I'm going to go ahead and close this issue as we've been unable to reproduce it. Feel free to reopen or reach out to our support team if you're still running into this issue.

Thanks,
@gwhelanLD

**Comment by kriss-campbell** [comment]
Hi @gwhelanLD 

Sorry, I just realised I've made a mistake, it's not LD causing this issue, please ignore
