### ISSUE TITLE
Eliminate BlocksKit

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/ios-client#26]
We would like to reduce the number of third-party library dependencies. BlocksKit is an obvious candidate for elimination.

**Comment by cmavromoustakos** [comment]
Fixed in #29

**Comment by anton-matosov** [comment]
And it conflicts with ReactiveCocoa causing crashes. =)
When do you plan to release this change to pod trunk?

**Comment by jkodumal** [comment]
Hi @anton-matosov -- we've pushed 0.4.2-beta with this change in place.
