### ISSUE TITLE
Increased crashes with iOS SDK v5.4.4

### ISSUE THREAD

**Issue by justinvallely** [launchdarkly/ios-client#261]
**Is this a support request?**
No.

**Describe the bug**
We updated the Launch Darkly iOS client SDK to version 5.4.4. This in turn updated LDSwiftEventSource to version 1.3.0.
We are now seeing a large spike in crashes related to LDSwiftEventSource `EventSourceDelegate.connect()`.

**To reproduce**
The logs aren't symbolicated so reproduction path is difficult to determine. We're still investigating if the missing dSYMs are related to this version bump or something larger.

**Expected behavior**
Launch Darkly doesn't contribute any new crashes in our app.

**Logs**

Example 1:
LDSwiftEventSource | closure # 1 in EventSourceDelegate.start() + 332
LDSwiftEventSource | EventSourceDelegate.connect() + 424
Crash

Example 2:
LDSwiftEventSource | partial apply for closure # 1 in EventSourceDelegate.reconnect() + 60
LDSwiftEventSource | EventSourceDelegate.connect() + 424
Crash

**SDK version**
5.4.4

**Language version, developer tools**
- Deployed with Xcode 13.1
- Swift 5

**OS/platform**
We're seeing crashes in iOS versions 12 through 15, however this could potentially be happening in iOS 11 and below. We don't support anything below 12.

We're seeing crashes on a wide range of iPhone and iPad devices.

**Comment by louis-launchdarkly** [comment]
Hello @justinvallely, thank you for reporting the issue. We will start investigating on our side, and please let us know if you find out anything about the missing dSYMs issue. Just to check, beyond the increased crashing, do you observe any other change of behavior?

Also, we will reach out if there are any follow-up questions we need to ask in order to reproduce the issue on our side.

_Filed Internally as 141175_

**Comment by justinvallely** [comment]
Hey @louis-launchdarkly! No other changes in behavior have been noticed. The missing dSYMs looks to be isolated to just this SDK however I did find dSYM bundles for both LaunchDarkly and LDSwiftEventSource in our build artifacts so I'll need to continue to explore why those didn't get uploaded to our crash reporter. Any chance they're invalid?

**Comment by louis-launchdarkly** [comment]
Hello @justinvallely, I am not super familiar with dSYMs, but if those are generated with your build artifacts, based on https://stackoverflow.com/questions/3656391/whats-the-dsym-and-how-to-use-it-ios-sdk, those should be correct/valid? There is also a link in that stackoverflow discussion top answer about how to use the dSYM.

Recently, there is another issue reported about more frequent crashing https://github.com/launchdarkly/ios-client-sdk/issues/262, have you seen a log message similar to `Task created in a session that has been invalidated` when your app crashes?

**Comment by gwhelanLD** [comment]
Hi @justinvallely,

We believe this should be resolved in the [5.4.5 release](https://github.com/launchdarkly/ios-client-sdk/releases/tag/5.4.5). Please give it a try, if it doesn't resolve these crashes feel free to reopen the GH issue.

Thanks,
@gwhelanLD
