### ISSUE TITLE
Crash logs from firebase - FlagSynchronizer.swift line 73

### ISSUE THREAD

**Issue by mehulios** [launchdarkly/ios-client#268]
We are facing this issue in launch dark iOS SDK.
These are the logs from firebase.

Crashed: com.launchdarkly.LDClient.isOnlineQueue
0  libobjc.A.dylib                0x1ee0 objc_msgSend + 32
1  LaunchDarkly                   0x43d50 FlagSynchronizer.isOnline.setter + 73 (FlagSynchronizer.swift:73)
2  LaunchDarkly                   0x46a3c protocol witness for LDFlagSynchronizing.isOnline.setter in conformance FlagSynchronizer + 4402735676 (<compiler-generated>:4402735676)
3  LaunchDarkly                   0x4ad1c closure #1 in LDClient.isOnline.setter + 72 (LDClient.swift:72)
4  LaunchDarkly                   0x5596c partial apply for thunk for @callee_guaranteed () -> () + 4402796908 (<compiler-generated>:4402796908)
5  LaunchDarkly                   0x4a87c thunk for @escaping @callee_guaranteed () -> () + 4402751612 (<compiler-generated>:4402751612)
6  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
7  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
8  LaunchDarkly                   0x4b84c LDClient.go(online:reasonOnlineUnavailable:completion:) + 69 (LDClient.swift:69)
9  LaunchDarkly                   0x59f74 partial apply for closure #1 in closure #1 in LDClient.internalSetOnline(_:completion:) + 136 (LDClient.swift:136)
10 LaunchDarkly                   0xbfb8 partial apply for thunk for @escaping @callee_guaranteed () -> () + 4402495416 (<compiler-generated>:4402495416)
11 LaunchDarkly                   0xbf98 partial apply for thunk for @escaping @callee_guaranteed () -> (@out ()) + 4402495384 (<compiler-generated>:4402495384)
12 LaunchDarkly                   0x61f0c thunk for @escaping @callee_guaranteed () -> () + 4402847500 (<compiler-generated>:4402847500)
13 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
15 libdispatch.dylib              0x15280 _dispatch_root_queue_drain + 680
16 libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
17 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
18 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**Comment by louis-launchdarkly** [comment]
Hello @mehulios, thank you for reporting this issue. We are looking at this in our current work for the next major release. And if this issue doesn't show up in that next release, we will investigate what we need to backport afterward.

**Comment by mehulios** [comment]
@louis-launchdarkly  Do we have any update on this issue?

**Comment by mehulios** [comment]
@louis-launchdarkly  do we have any update on this ?

**Comment by louis-launchdarkly** [comment]
Hello @mehulios, I am really sorry for missing the reply to this. I wonder does the 6.x SDK released on May 4, 2022, fixed your issue? Currently, the iOS SDK 9.0.0 was released last week and had quite a bit of rearchitecting in place. Please let us know via https://support.launchdarkly.com/hc/en-us if you still encounter the issue - LaunchDarkly support team has dedicated engineers for customer issues and will not miss a reply like this. Once again, I am really sorry for this late reply.
