### ISSUE TITLE
FlagSynchronizer.swift - Line 69

### ISSUE THREAD

**Issue by RagulMLTataDigital** [launchdarkly/ios-client#276]
Please find the logs and OS version as below.

**iOS version - 15.5.0**

Crashed: com.launchdarkly.LDClient.isOnlineQueue
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  LaunchDarkly                   0x3a0b0 isOnline.set + 69 (FlagSynchronizer.swift:69)
2  LaunchDarkly                   0x3d794 isOnline.set + 4413659028 (<compiler-generated>:4413659028)
3  LaunchDarkly                   0x41b1c <name omitted> + 63 (LDClient.swift:63)
4  LaunchDarkly                   0x4b858 <name omitted> + 4413716568 (<compiler-generated>:4413716568)
5  LaunchDarkly                   0x416d8 <name omitted> + 4413675224 (<compiler-generated>:4413675224)
6  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
7  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
8  LaunchDarkly                   0x4264c go + 60 (LDClient.swift:60)
9  LaunchDarkly                   0x4fa10 <name omitted> + 127 (LDClient.swift:127)
10 LaunchDarkly                   0x8528 <name omitted> + 4413441320 (<compiler-generated>:4413441320)
11 LaunchDarkly                   0x8508 <name omitted> + 4413441288 (<compiler-generated>:4413441288)
12 LaunchDarkly                   0x5b1f4 <name omitted> + 4413780468 (<compiler-generated>:4413780468)
13 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
15 libdispatch.dylib              0x15280 _dispatch_root_queue_drain + 680
16 libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
17 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
18 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**Comment by keelerm84** [comment]
Thank you for reporting this issue. Can you confirm which version of the SDK you are using?

**Comment by RagulMLTataDigital** [comment]
LaunchDarkly (6.1.0)

**Comment by keelerm84** [comment]
I am closing this issue. This conversation was long since moved to our support channels and handled there.
