### ISSUE TITLE
Not able to retrieve LDValue from Object.

### ISSUE THREAD

**Issue by nagarajanpn** [launchdarkly/ios-client#278]
Pod Version : ### pod 'LaunchDarkly', '~> 6.1'
Code : 
**LDClient.get()?.jsonVariation(forKey: "MyMobileKey", defaultValue:nil)** 
Response : 
_Optional<LDValue>
  ▿ some : LDValue
    ▿ object : 3 elements
      ▿ 0 : 2 elements
        - key : "iOS"
        ▿ value : LDValue
          - bool : true
      ▿ 1 : 2 elements
        - key : "Android"
        ▿ value : LDValue
          - bool : true
      ▿ 2 : 2 elements
        - key : "Configs"
        ▿ value : LDValue
          ▿ object : 1 element
            ▿ 0 : 2 elements
              - key : "webLink"
              ▿ value : LDValue
                - string : "https://fffffffff.com"_
Issue: 
1. How to do JSONSerialization of the Above Object , that Object contains LDValue. 
2. Trying to do decode that json object but , during pass the json data facing error.
3. I am trying to convert LDvalue to dictionary or array i could not able to do. 

Kindly provide sample code.

**Comment by keelerm84** [comment]
1. How to do JSONSerialization of the Above Object , that Object contains LDValue.

An LDValue makes use of the [Encodable][1] protocol. It can be encoded like:

```swift
let result = try JSONEncoder().encode(variationResult)
```

If you want to include that LDValue in another struct, that struct can use the Encodable protocol as well and the LDValue should serialize without issue.

```swift
struct ExampleStruct: Encodable {
    public var name: String
    public var value: LDValue
}

let example = ExampleStruct.init(name: "Example", value: variationResult)
let jsonString = try JSONEncoder().encode(example)
```

2. Trying to do decode that json object but , during pass the json data facing error.

I'm not sure what you mean by this. Could you please explain in more detail?

3. I am trying to convert LDvalue to dictionary or array i could not able to do.

The LDValue is an [Enumeration with an associated value][2]. To unpack the values within the LDValue, you need to do some sort of pattern matching. For example, if you want to convert your result into a dictionary, you can do:

```swift
guard case .object(let dictionary) = variationResult
else { return }

print(dictionary["iOS"])
```

[1]: https://developer.apple.com/documentation/swift/encodable
[2]: https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

**Comment by jskrepnek** [comment]
> 1. How to do JSONSerialization of the Above Object , that Object contains LDValue.
> 
> An LDValue makes use of the [Encodable](https://developer.apple.com/documentation/swift/encodable) protocol. It can be encoded like:
> 
> ```swift
> let result = try JSONEncoder().encode(variationResult)
> ```
> 

@keelerm84 Is this possible in Objective-C?  If not, is there any alternative in Objective-C beside iterating through arrays and dictionaries to convert each element/value from an LDValue to a corresponding type that is serializable?

**Comment by nagarajanpn** [comment]
Thanks for your mail

**Comment by keelerm84** [comment]
> @keelerm84 Is this possible in Objective-C? If not, is there any alternative in Objective-C beside iterating through arrays and dictionaries to convert each element/value from an LDValue to a corresponding type that is serializable?

No, I do not believe so. Objective-C's NSJSONSerialization seems quite restrictive. For it to work, we would need to add a method on the evaluation result which could represent the entire structure as Foundation objects. This would in turn require us to do the same for LDValue, which requires traversing that entire structure.
