### ISSUE TITLE
The first run of the app on Real iPhone [Not Simulator] Doesn't get any flags, the SDK use the default value

### ISSUE THREAD

**Issue by IslamAbdelAziz** [launchdarkly/ios-client#292]
## **Describe the bug**
Simply: The first run of the app on Real iPhone [Not Simulator] Doesn't get any flags, the SDK use the default value I set here 
boolVariation(forKey: "flagValue", defaultValue: false)

## **To Reproduce**
1. just run the app (which contains LD SDK inside) on real iPhone for the first time [remove it of it is already installed on the iPhone]

## **Expected behavior**
To receive the actual values from LD dashboard not to get the default values I set in the code.

##**Screenshots**
No screenshots, But this is an error from logs
[connection] nw_resolver_start_query_timer_block_invoke [C9.1.1] Query fired: did not receive all answers in time for clientstream.launchdarkly.com:443

**Smartphone (please complete the following information):**
 - Device: [any iPhone]
 - OS: [iOS 16.3]

**Additional context**

**Comment by louis-launchdarkly** [comment]
Hello @IslamAbdelAziz, thank you for reaching out. This looks like a support request - please file a support ticket [here](https://support.launchdarkly.com/hc/en-us) and our support engineer can help you out.
