### ISSUE TITLE
Change static type of sharedInstance

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/ios-client#31]
Feedback from a user:

in the SDK the sharedInstance is declared like this 
- (id)sharedInstance; 
  Should be declared with a type like this 
- (LDClient*)sharedInstance; 
  or this 
- (instancetype)sharedInstance; 
  This is because the current way does not retain the type of the object and makes it more difficult to work with (no intellisense) as we causes warnings on name conflicts with other objects

**Comment by danialzahid94** [comment]
This has been changed to `(LDClient *)sharedInstance;` since 2eb2a75
