### ISSUE TITLE
Carthage build fails with Xcode 15

### ISSUE THREAD

**Issue by alexfanatics** [launchdarkly/ios-client#311]
**Is this a support request?**
No

**Describe the bug**
Carthage build fails with Xcode 15. It appears they dropped iOS 11 support, so the deployment target needs to be updated.

**To reproduce**
` carthage update --use-xcframeworks --platform ios`

**Expected behavior**
Carthage build should succeed.

**Logs**
`.../Carthage/Checkouts/ios-client-sdk/LaunchDarkly.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99.`
**SDK version**
9.1.1

**Language version, developer tools**
`Xcode 15.0 | Release | 15A240d`

**OS/platform**
Mac OS 13.5.2 (22G91)

**Comment by tanderson-ld** [comment]
@alexfanatics , thank you for bringing this to our attention.  We'll look into it soon.  Do you have a workaround at the moment?  Also, did this happen as a result of updating to XCode15 or updating to version 9.1.1 of the SDK?

**Comment by alexfanatics** [comment]
1. SDK version 9.1.1 builds without issue using Carthage on Xcode 14.3.1
2. I've validated that bumping the minimum deployment target to iOS 12 enables Xcode 15 to build the SDK using Carthage correctly. 

Commit: https://github.com/launchdarkly/ios-client-sdk/commit/383ac8a3c16adefb098c5e6dde0aa18841c63364

Cartfile: `github "alexfanatics/ios-client-sdk" == 9.1.199`

command: `carthage update --use-xcframeworks --platform ios`

**Comment by tanderson-ld** [comment]
@alexfanatics , this has been filed internally as 218049.  We will prioritize accordingly.  Thank you for raising this issue!

**Comment by dayton-bobbitt** [comment]
Hi @tanderson-ld, I'm experiencing the same issue. Is there any information you can provide on when this will be resolved? I'm trying to decide if it's worth fixing the issue in a fork like @alexfanatics did or to just wait for the next release.

Thanks!

**Comment by tanderson-ld** [comment]
@dayton-bobbitt , this will be next on my list after my current work.  No guarantee on timeline, but likely in the next two weeks.

**Comment by tanderson-ld** [comment]
@dayton-bobbitt , changes should be going into a release within the next few days.

**Comment by tanderson-ld** [comment]
@alexfanatics and @dayton-bobbitt , we just released 9.2.0 that should address this issue.  Please give it a test and let us know the result.  We'll likely close this issue in the next few days if we don't hear back.  Thank you again for telling us about this issue.

**Comment by tanderson-ld** [comment]
Closing as we believe this is fixed.
