### ISSUE TITLE
On version 9.4.1 the logs are excessive by default and I see no way to disable them.

### ISSUE THREAD

**Issue by mcmurrym** [launchdarkly/ios-client#350]
**Describe the bug**
In version 9.4.1 the logs are excessive by default and I see no way to disable them.

**To reproduce**
Use version 9.4.1

**Expected behavior**
The ability to disable logs, or reduce to errors only in development

**Logs**
If applicable, add any log output related to your problem.

**Library version**
9.4.1

**XCode and Swift version**
Xcode 15.3.0 Swift 5.10

**Platform the issue occurs on**
iPhone, iPad, macOS, tvOS, or watchOS.

**Additional context**

**Comment by keelerm84** [comment]
By default, the SDK makes use of Logger with subsystem "com.launchdarkly" and category of "ios-client-sdk".

You can provide your own logger (or disable it entirely) using the `Config.logger` property.

```swift
config.logger = .disabled
```

**Comment by mcmurrym** [comment]
> By default, the SDK makes use of Logger with subsystem "com.launchdarkly" and category of "ios-client-sdk".
> 
> You can provide your own logger (or disable it entirely) using the `Config.logger` property.
> 
> ```swift
> config.logger = .disabled
> ```

This works. Thank you.
