### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by itsyasirali** [launchdarkly/ios-client#358]
Hello Launch Darkly Team,

I hope this message finds you well. I would like to draw your attention to an important update required by the App Store. Starting May 1, 2024, a privacy manifest will be mandatory for all apps. Given the ongoing development and support for your SDK, integrating this feature would be highly beneficial for ensuring compliance with the new App Store guidelines. This addition would greatly help developers like us in continuing to provide seamless services through our applications. We appreciate your attention to this matter and look forward to any updates you can provide.

Thank you for your continued support.

**Comment by keelerm84** [comment]
We introduced a [PrivacyManifest](https://github.com/launchdarkly/ios-client-sdk/blob/v9/LaunchDarkly/LaunchDarkly/PrivacyInfo.xcprivacy) in v9.4.0.

Were there additional changes you require?

**Comment by itsyasirali** [comment]
Thanks @keelerm84 

It was overlooked by myself. Seems like its ok, but if anything further is needed I will let you know.

**Comment by choulepoka** [comment]
@yasiraliraj I have just tried it, and xcode is not picking up the privacy manifest, because it is not included in the package. 

<img width="803" alt="Screenshot 2024-03-25 at 14 46 03" src="https://github.com/launchdarkly/ios-client-sdk/assets/91069435/26381b5f-21f4-483b-9ce9-aeb678776e4b">

**Comment by choulepoka** [comment]
You need to update the `Package.swift`, and add `resources: [.copy("PrivacyInfo.xcprivacy")])` to the `LaunchDarkly` target, and then it will work as intended.
