### ISSUE TITLE
Ability to configure logging

### ISSUE THREAD

**Issue by patrickcapadmi** [launchdarkly/ios-client#359]
The SDK currently writes a large number of logs to the console for all of it's internal operations. This is helpful for debugging issues with Launch Darkly but a lot of spam to the console otherwise.

This seems to have been introduced with SDK version 9.4.0 with this change: https://github.com/launchdarkly/ios-client-sdk/pull/340

I'd like the ability via logging levels or a boolean flag to customise the levels of or enable/ disable logging from the SDK.

**Additional context**
SDK version 9.4.0+

**Comment by tanderson-ld** [comment]
Hi @patrickcapadmi, thank you for reaching out.  Does the config option posted in [this closed issue](https://github.com/launchdarkly/ios-client-sdk/issues/350) fit your needs?

**Comment by patrickcapadmi** [comment]
Ahh, thanks looks like that will do the trick.

I'd possibly suggest adding info on that to this page in the docs as I'd assumed it wasn't possible given the iOS Client SDK is missing - https://docs.launchdarkly.com/sdk/features/logging

**Comment by tanderson-ld** [comment]
Thank you for bringing that to our attention.  We didn't realize it was missing over there.  Tracking as 238017 internally.
