### ISSUE TITLE
Status stays receiving response body, never completes.

### ISSUE THREAD

**Issue by keyvanygh** [launchdarkly/ios-client#389]
**Describe the bug**
Our Analytics tools showing 99% failure on launchdarkly http requests, which is the result of the request not completing, they are then closed with error when the app is removed from memory.
<img width="1387" alt="Screenshot 2024-05-30 at 3 14 51 AM" src="https://github.com/launchdarkly/ios-client-sdk/assets/24761725/ffa25658-2434-43e5-b19b-f79253a5b35f">
is it safe to ignore this? is this an expected behavior?

**To reproduce**
no steps.

**Expected behavior**
api call change status to complete.

**Library version**
9.1.1

**Comment by tanderson-ld** [comment]
Hello @keyvanygh , this is expected.  When in streaming mode which is the default, the SDK uses Server Sent Events for streaming flag changes to the SDK which under ideal conditions are long lived responses.
