### ISSUE TITLE
Setting a nil context breaks LaunchDarkly

### ISSUE THREAD

**Issue by kylebrowning** [launchdarkly/ios-client#395]
**Describe the bug**
Title really says it all, if you omit context in the `start` function 
```swift
        LDClient.start(
            config: config,
            context: nil,
            startWaitSeconds: 5
        )
```
Launch Darkly will refuse to launch.

**Expected behavior**

**Logs**
```
Waiting 25.457 seconds before reconnecting...
Starting EventSource client
Initial reply received
Unsuccessful response: 400
State: closed -> closed
Waiting 16.171 seconds before reconnecting...
```
**Library version**
The version that you are using.

**XCode and Swift version**
Xcode 15.4 Swift 5.0
**Platform the issue occurs on**
iPhone

**Additional context**
Can you provide details on what happens in the case of failure for 
```swift
        guard case .success(let context) = contextBuilder.build() else { return }
```
Having to always provide a context is a bit cumbersome, and if LaunchDarkly client fails to startup it could have pretty bad consequences downstream.

**Comment by keelerm84** [comment]
@kylebrowning I'm sorry you're experiencing an issue. Can you tell me which version of the SDK you are using?

I did test the latest version and it seems to work just fine without an explicit context, so maybe this is an issue with an older version.

**Comment by kylebrowning** [comment]
im on the latest, this is my first time using LD, and I just included it in the project

**Comment by keelerm84** [comment]
@kylebrowning 

If I use the [hello-ios-swift](https://github.com/launchdarkly/hello-ios-swift) repository, and provide a `nil` value for the `context` property, everything seems to operate as expected for me.

Can you perform the same test and see if it is working for you?

**Comment by kylebrowning** [comment]
ugh, had to install cocoa pods :( but yes I get the same issue
```
Getting current session token
State: raw -> connecting
Starting EventSource client
Identifying user to system
Initial reply received
Unsuccessful response: 400
State: connecting -> closed
Waiting 1.620 seconds before reconnecting...
Starting EventSource client
Initial reply received
Unsuccessful response: 400
State: closed -> closed
Waiting 2.486 seconds before reconnecting...
Starting EventSource client
Initial reply received
```

**Comment by keelerm84** [comment]
@kylebrowning sorry for requiring the install.

If that isn't working for you either, then that seems to suggest something specific to your account.

Can you confirm you are providing the mobile key (i.e. key is prefixed with `mob-`)?

**Comment by kylebrowning** [comment]
Yup, adding the context back in works

**Comment by keelerm84** [comment]
At this point, I don't think I can easily troubleshoot this without having some more information related to your account.

Would you mind opening a support ticket? Please reference this GH issue so support can ensure I'm notified when this comes in.

In your ticket, please make sure you include the environment you are using for your test. If possible, it would be useful if you could also enable "Enhanced Support" through the UI. This will allow us to take a look at your configuration and determine if there is something related to its current state that is causing your issue.
