### ISSUE TITLE
Core Data concurrency violation

### ISSUE THREAD

**Issue by Automatt** [launchdarkly/ios-client#49]
When we compile and run our app with this argument passed during launch:

`-com.apple.CoreData.ConcurrencyDebug 1`

Code called from within LaunchDarkly stops the debugger.  This suggests that LD's client is violating thread concurrency rules for Core Data access.

https://pawanpoudel.svbtle.com/fixing-core-data-concurrency-violations

**Comment by jkodumal** [comment]
Sorry for the late response on this-- this issue should be obviated by our upcoming release-- we're eliminating the use of Core Data entirely.

**Comment by drichelson** [comment]
Resolved in 1.0.0 @Automatt please let us know if this fixed the problem.

**Comment by Automatt** [comment]
This issue is resolved - thanks
