### ISSUE TITLE
compile errors because of missing DarklyConstants.m file

### ISSUE THREAD

**Issue by RonnyFenrich** [launchdarkly/ios-client#56]
We've noticed that our builds fail now on clean systems using v1.0 of LaunchDarkly with error messages like: 

```
Undefined symbols for architecture armv7:
  "_kIphone", referenced from:
      +[LDUtil getDeviceAsString] in LDUtil.o
```

It looks like the DarklyConstants.m is missing in the current repository. That file contains the concrete implementation for the external variables defined in DarklyConstants.h

**Comment by jkodumal** [comment]
Thanks @RonnyFenrich -- we're working on this ASAP.

**Comment by danialzahid94** [comment]
This should be fixed in release 1.0.1

**Comment by phin** [comment]
@danialzahid94 1.0.1 isn't available on Cocoapods yet, we also have the same issue and reverted all our code back to 0.4.4

**Comment by jkodumal** [comment]
We're releasing 1.0.1 now.

**Comment by jkodumal** [comment]
1.0.1 should be available via cocoapods now.

**Comment by RonnyFenrich** [comment]
👍
All fixed now. Thanks.
