### ISSUE TITLE
Incompatible pointer to integer conversion warnings in LDUserModel.m

### ISSUE THREAD

**Issue by llaborcz** [launchdarkly/ios-client#59]
In the file LDUserModel.m there are is the following compiler warning

LDUserModel.m:104:24: Incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id _Nullable'

Looking at the code:

```
    self.anonymous = [dictionary objectForKey: kAnonymousKey];
```

The return value of objectForKey: is being assigned to a BOOL value:

@property (nonatomic, assign) BOOL anonymous;

Can this code be fixed so that it explicitly sets the BOOL value rather than relying on the implicit assignment?

**Comment by justinucd** [comment]
We'll look into this now :) thanks for pointing it out

**Comment by llaborcz** [comment]
Thanks - I opened an almost duplicate issue against another file as well. We've got a zero new warnings policy on our build system and this and the other issue break us.

**Comment by justinucd** [comment]
No problem, we'll make these changes shortly
