### ISSUE TITLE
Build warnings in LDConfig.h and LDRequestManager.h

### ISSUE THREAD

**Issue by llaborcz** [launchdarkly/ios-client#69]
![image](https://cloud.githubusercontent.com/assets/7701901/18762618/cfd71b70-8109-11e6-9199-9a1cc079913a.png)
There are many build warnings in LDRequestManager.h and LDConfig.h caused by not declaring the ARC attribtues for properties.

We've got a zero warning policy and this is causing our build to fail

**Comment by justinucd** [comment]
Hey there - thanks for bringing this up. May I ask if you're using the latest version of the SDK?

**Comment by llaborcz** [comment]
Good question - let me find out. I'm just the messenger on this :) I'll get back to you tomorrow.
Thanks

**Comment by justinucd** [comment]
Ok cool :) Do you mind creating a support ticket on our site?  You can do so here: https://support.launchdarkly.com/ "Create Ticket" or you can login to your LaunchDarkly account and use the Support tab at the bottom right to create a ticket.

**Comment by llaborcz** [comment]
Ok thanks will do

**Comment by arun251** [comment]
This issue is obsolete.
