### ISSUE TITLE
Readme is incorrect

### ISSUE THREAD

**Issue by kdawgwilk** [launchdarkly/ios-client#74]
This line no longer works:
```objective-c
[[LDClient sharedInstance] start:config];
```
and needs to be:
```objective-c
LDUserBuilder *user = [[LDUserBuilder alloc] init];
 user = [user withKey:@"aa0ceb"];
    
[[LDClient sharedInstance] start:config userBuilder:user];
```
it might be good to mention that the user can also be nil and annotating the Objective-C methods as such would help as well explained here: 

https://developer.apple.com/swift/blog/?id=25
These annotations would also greatly help Swift interop

**Comment by justinucd** [comment]
Thanks for pointing these out! We'll take a look and make the appropriate edits/additions.

**Comment by arun251** [comment]
We fixed this a while back. Thanks again for reporting this.
