### ISSUE TITLE
Incorrect docs for Swift

### ISSUE THREAD

**Issue by kdawgwilk** [launchdarkly/ios-client#75]
To update the user context in Swift you have to do this ugly thing:
```swift
(LDClient.sharedInstance() as! LDClient).updateUser(user)
```
rather than what it says in the docs:
```swift
LDClient.sharedInstance().updateUser(user)
```
this is because `sharedInstance()` returns `AnyObject`

**Comment by justinucd** [comment]
Thanks! We'll look into this ASAP.

**Comment by danialzahid94** [comment]
Hey @kdawgwilk. Are you sure you're not able to use `LDClient.sharedInstance().updateUser(user)`?

In one of our demo apps, we are currently using the same syntax. If you're still facing the issue, can you please mention the Swift version you are using?

**Comment by kdawgwilk** [comment]
We are using Swift 2.3.  I just removed the cast and it seems to be compiling fine now, maybe a derived data delete fixed it sometime between then and now ¯\_(ツ)_/¯
