### ISSUE TITLE
Significant performance issue in createFeatureEvent: caused by NSKeyedArchiver/NSKeyedUnarchiver

### ISSUE THREAD

**Issue by adc-amatosov** [launchdarkly/ios-client#76]
On every feature flag check the following like is executed:
[[LDDataManager sharedManager] createFeatureEvent: featureKey keyValue:returnValue defaultKeyValue:fallback]; which is SYNCHRONOUSLY on the MAIN THREAD unarchiving a dictionary of objects, sets 1 key and archives all of them back.
This causes 70-90% CPU load on iPhone 6+ if called just 2 times a second.
This is a blocker for our release.

**Comment by justinucd** [comment]
Thanks for pointing this out - I'm going to create a support ticket so we can get this fixed ASAP - which email should I add to the ticket?

**Comment by adc-amatosov** [comment]
amatosov.ctr at ten-x dot com

**Comment by arun251** [comment]
This was fixed and released in 2.1.0.
