### ISSUE TITLE
 userDidUpdate is not letting user know which flag got change

### ISSUE THREAD

**Issue by soni-mukesh** [launchdarkly/ios-client#77]
LaunchDarkly iOS Library's  ClientDelegate's userDidUpdate is not letting user know which flag got change.
how do i get to know ? it is difficult to check each and every flag and maintain them old value.

however in Android it is clear 

public interface FeatureFlagChangeListener {
	void onFeatureFlagChange(String flagKey);
}

here flagKey tells which key got changed therefore user can get the fresh value for this key.

However in iOS userDidUpdate doesn't tell which key?

**Comment by danialzahid94** [comment]
Hi @soni-mukesh. This has been addressed in #78 . You can update to the latest version to use that.
